services:
  web:
    build: .
    container_name: saude-ia-web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/app/staticfiles
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: saude-ia-db
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: saude-ia-redis
    restart: unless-stopped

  celery-worker:
    build: .
    container_name: saude-ia-celery-worker
    command: celery -A config worker -l info
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
    restart: unless-stopped

  celery-beat:
    build: .
    container_name: saude-ia-celery-beat
    command: celery -A config beat -l info
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
    volumes:
      - celery_beat_schedule:/app
    restart: unless-stopped

  nginx:
    image: nginx:1.27
    container_name: saude-ia-nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles:ro
      - ./nginx.conf:/etc/nginx/conf.d/custom.conf:ro
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: saude-ia-portainer
    restart: always
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  postgres_data:
  celery_beat_schedule:
  static_volume:
  portainer_data: