version: "3.9"

services:
  web:
    build: .
    container_name: saude-ia-web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/app/staticfiles
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: saude-ia-db
    env_file:
      - .env.prod
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: saude-ia-redis
    restart: unless-stopped

  celery-worker:
    build: .
    container_name: saude-ia-celery-worker
    command: celery -A config worker -l info
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
    restart: unless-stopped

  celery-beat:
    build: .
    container_name: saude-ia-celery-beat
    command: celery -A config beat -l info
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
    restart: unless-stopped
    volumes:
      - celery_beat_schedule:/app

  nginx:
    image: nginx:1.27
    container_name: saude-ia-nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

volumes:
  postgres_data:
  celery_beat_schedule:
  static_volume: